name: learn-github-actions
on: [pull_request]
jobs:
  add-code:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Log Submission time
        run: echo "Submitted at " $(date)
      - name: List files
        run: ls -alh
      - name: Run program (55)
        run: python3 $(find . -name '*.py' | head -n 1) 55
        shell: bash
      - name: Run program ("Grey Poupon")
        run: python3 $(find . -name '*.py' | head -n 1) "Grey Poupon"
        shell: bash
